-- CreateTable
CREATE TABLE `FirewallRule` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `srcIp` VARCHAR(191) NOT NULL,
    `dstIp` VARCHAR(191) NOT NULL,
    `protocol` VARCHAR(191) NOT NULL DEFAULT 'ANY',
    `action` VARCHAR(191) NOT NULL DEFAULT 'BLOCK',
    `description` VARCHAR(191) NOT NULL DEFAULT '',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
